import { NextUiProviders } from '@/providers/nextui.provider';
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Comfortaa, Sevillana, Noto_Sans_Javanese } from 'next/font/google'

const comfortaa = Comfortaa({ subsets: ['latin', "cyrillic"], display: "swap", variable: "--font-comfortaa" });
const sevillana = Sevillana({ subsets: ['latin'], display: "swap", weight: "400", variable: "--font-sevillana" })
const javanese = Noto_Sans_Javanese({ subsets: ["javanese"], display: "swap", variable: "--font-javanese" });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark ${comfortaa.variable} ${sevillana.variable} ${javanese.variable}`}>
        <NextUiProviders>
          {children}
        </NextUiProviders>
      </body>
    </html>
  )
}
